/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unfp;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.fxml.FXMLLoader;

public class App extends Application{
    public static void main(String[] args) {        
        launch();
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader initialViewLoader = new FXMLLoader(getClass().getClassLoader().getResource("initial_View.fxml"));
        Parent root = initialViewLoader.load();
        FilesModel fm = new FilesModel();
        InitialViewController vc = initialViewLoader.getController();
        vc.initModel(fm);

        Scene scene = new Scene(root, 500, 300);
        primaryStage.setTitle("HoiHoiRipper");
        primaryStage.setScene(scene);
        primaryStage.setOnCloseRequest(e->Platform.exit());
        primaryStage.show();
    }
}
